openapi: 3.0.4
info:
  title: Play Off Rentals
  version: 2.0.0
  description: Play Off Rentals is a full stack project that focuses simulating the web store of a local business. The business, 'Play Off Rentals' is a rental service for arcade machines, allowing people in the 'area' to build their own 'arcade' by renting the machines in their catalog.
servers:
  - url: http://localhost:8000/api
    description: Development server
paths:
  /map/locations:
    get:
    
  # https://editor.swagger.io/